name: update-aqua-checksums
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - config/.config/aquaproj-aqua/aqua-checksums.json
      - config/.config/aquaproj-aqua/aqua.yaml
env:
  AQUA_DIR: config/.config/aquaproj-aqua
jobs:
  update-aqua-checksums:
    # aquaproj/update-checksum-workflow doesn't work for somewhat
    # uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@437067ad2fba9ba8ed8454cf207f2532432d4e28 # v1.0.2
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        # Install ghcp
        with:
          aqua_version: v2.30.0
          working_directory: ${{ env.AQUA_DIR }}
      - run: ghcp -v
